#cloud-config

hostname: test-hostname
coreos:
  update:
    group: stable
    reboot-strategy: best-effort

  etcd:
    discovery: https://discovery.etcd.io/<token>
    addr: $private_ipv4:4001
    peer-addr: $private_ipv4:7001
    name: name

  fleet:
    public-ip: $private_ipv4
    metadata: name=%H

  units:
    - name: etcd.service
      command: start

    - name: fleet.service
      command: start

#Private Network settings for Linode. 
    - name: private-networking.service
      command: start
      content: |
        [Unit]
        Description=Linode Private Networking.
        After=network.target
        Before=docker.service
        
        [Service]
        Type=oneshot
        RemainAfterExit=yes
        # Set Private Network
        ExecStartPre=-/usr/bin/ifconfig eth0 add $private_ipv4
        ExecStart=-/usr/bin/ifconfig eth0:0 netmask 255.255.128.0

users:
  - name: username
    primary-group: wheel
    groups: [ sudo, docker ]
    ssh-authorized-keys:
      - ssh-rsa AAAA*******

write_files:
# Environment Variables
  - path: /etc/environment
    content: |
      COREOS_PUBLIC_IPV4=$public_ipv4
      COREOS_PRIVATE_IPV4=$private_ipv4
